config/routes.rb
Rails.application.routes.draw do
  resources :providerservices
  resources :providerprofiles
  resources :masterservices
  get 'pages/home'
  get 'pages/maptest'

  resources :profiles
  devise_for :providers
  devise_for :customers
  
  root 'pages#home'

end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :customer
  has_many :services
  accepts_nested_attributes_for :services, reject_if: :all_blank, allow_destroy: true
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  before_action :set_services_dropdown, only: [:new, :edit]
  before_action :authenticate_customer!

  # GET /profiles
  # GET /profiles.json
  def index
    if current_customer.profile
      redirect_to profile_path(current_customer.profile)
    else
      redirect_to new_profile_path
    end
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = current_customer.create_profile
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_customer.profiles.new(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:name, :address, :customer_id, services_attributes: [:id, :name, :description, :_destroy])
    end
    
    def set_services_dropdown
      @service_dropdown = Masterservice.all.map{ |s| [ s.name ] }
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<div class="row">
  <%= form_for(@profile) do |f| %>
    <% if @profile.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@profile.errors.count, "error") %> prohibited this profile from being saved:</h2>
  
        <ul>
        <% @profile.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :address %><br>
      <%= f.text_field :address, class: "form-control" %>
    </div>
      <%= f.hidden_field :customer_id %>
    <div class="col">
      <h3>Services Required</h3>
      <%= f.fields_for :services do |service| %>
        <%= render 'service_fields', f: service %>
      <% end %>
    </div>
    <div class="row">
      <%= link_to_add_association 'Add Another Service', f, :services, class: "btn btn-success" %>
    </div>
      <br>  <%= f.submit nil, class: "btn btn-primary" %>
    </div>
  <% end %>
  <br>

app/views/profiles/_service_fields.html.erb
<div class="nested-fields" %>
    <div class="row">
      <div class="form-group">
        <%= f.label :name %>
        <%= f.select :name, @service_dropdown, class: "form-control" %>
        <%= link_to_remove_association "Remove Service", f, class: "btn btn-danger" %>
      </div>
    </div>
</div>

app/views/profiles/edit.html.erb
<h1>Editing Profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @profile %> |
<%= link_to 'Back', profiles_path %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Customer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= @profile.name %></td>
        <td><%= @profile.address %></td>
        <td><%= link_to 'Show', @profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(@profile) %></td>
        <td><%= link_to 'Destroy', @profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
  </tbody>
</table>
<br>

app/views/profiles/new.html.erb
<h1>New Profile</h1>

<%= render 'form' %>

<%= link_to 'Back', profiles_path %>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @profile.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @profile.address %>
</p>

<p>
  <strong>Services</strong>
  <% @profile.services.each do |service| %>
    <%= service.name %>
    <%= service.description %>
  <% end %>
</p>

<%= link_to 'Edit', edit_profile_path(@profile) %> |
<%= link_to 'Back', pages_maptest_path %>