config/routes.rb
Rails.application.routes.draw do
  resources :providerservices
  resources :providerprofiles
  resources :masterservices
  get 'pages/home'
  get 'pages/maptest'

  resources :profiles
  devise_for :providers
  devise_for :customers
  
  root 'pages#home'

end

app/models/providerservice.rb
class Providerservice < ActiveRecord::Base
  belongs_to :providerprofile
end

app/controllers/providerservices_controller.rb
class ProviderservicesController < ApplicationController
  before_action :set_providerservice, only: [:show, :edit, :update, :destroy]

  # GET /providerservices
  # GET /providerservices.json
  def index
    @providerservices = Providerservice.all
  end

  # GET /providerservices/1
  # GET /providerservices/1.json
  def show
  end

  # GET /providerservices/new
  def new
    @providerservice = Providerservice.new
  end

  # GET /providerservices/1/edit
  def edit
  end

  # POST /providerservices
  # POST /providerservices.json
  def create
    @providerservice = Providerservice.new(providerservice_params)

    respond_to do |format|
      if @providerservice.save
        format.html { redirect_to @providerservice, notice: 'Providerservice was successfully created.' }
        format.json { render :show, status: :created, location: @providerservice }
      else
        format.html { render :new }
        format.json { render json: @providerservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /providerservices/1
  # PATCH/PUT /providerservices/1.json
  def update
    respond_to do |format|
      if @providerservice.update(providerservice_params)
        format.html { redirect_to @providerservice, notice: 'Providerservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @providerservice }
      else
        format.html { render :edit }
        format.json { render json: @providerservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /providerservices/1
  # DELETE /providerservices/1.json
  def destroy
    @providerservice.destroy
    respond_to do |format|
      format.html { redirect_to providerservices_url, notice: 'Providerservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_providerservice
      @providerservice = Providerservice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def providerservice_params
      params.require(:providerservice).permit(:name, :description, :providerprofile_id)
    end
end

app/helpers/providerservices_helper.rb
module ProviderservicesHelper
end

app/views/providerservices/_form.html.erb
<%= form_for(@providerservice) do |f| %>
  <% if @providerservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@providerservice.errors.count, "error") %> prohibited this providerservice from being saved:</h2>

      <ul>
      <% @providerservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :providerprofile_id %><br>
    <%= f.text_field :providerprofile_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/providerservices/edit.html.erb
<h1>Editing Providerservice</h1>

<%= render 'form' %>

<%= link_to 'Show', @providerservice %> |
<%= link_to 'Back', providerservices_path %>

app/views/providerservices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Providerservices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Providerprofile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @providerservices.each do |providerservice| %>
      <tr>
        <td><%= providerservice.name %></td>
        <td><%= providerservice.description %></td>
        <td><%= providerservice.providerprofile %></td>
        <td><%= link_to 'Show', providerservice %></td>
        <td><%= link_to 'Edit', edit_providerservice_path(providerservice) %></td>
        <td><%= link_to 'Destroy', providerservice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Providerservice', new_providerservice_path %>

app/views/providerservices/new.html.erb
<h1>New Providerservice</h1>

<%= render 'form' %>

<%= link_to 'Back', providerservices_path %>

app/views/providerservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @providerservice.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @providerservice.description %>
</p>

<p>
  <strong>Providerprofile:</strong>
  <%= @providerservice.providerprofile %>
</p>

<%= link_to 'Edit', edit_providerservice_path(@providerservice) %> |
<%= link_to 'Back', providerservices_path %>