config/routes.rb
Rails.application.routes.draw do
  resources :providerservices
  resources :providerprofiles
  resources :masterservices
  get 'pages/home'
  get 'pages/maptest'

  resources :profiles
  devise_for :providers
  devise_for :customers
  
  root 'pages#home'

end

app/models/masterservice.rb
class Masterservice < ActiveRecord::Base
end

app/controllers/masterservices_controller.rb
class MasterservicesController < ApplicationController
  before_action :set_masterservice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_provider!

  # GET /masterservices
  # GET /masterservices.json
  def index
    @masterservices = Masterservice.all
  end

  # GET /masterservices/1
  # GET /masterservices/1.json
  def show
  end

  # GET /masterservices/new
  def new
    @masterservice = Masterservice.new
  end

  # GET /masterservices/1/edit
  def edit
  end

  # POST /masterservices
  # POST /masterservices.json
  def create
    @masterservice = Masterservice.new(masterservice_params)

    respond_to do |format|
      if @masterservice.save
        format.html { redirect_to @masterservice, notice: 'Masterservice was successfully created.' }
        format.json { render :show, status: :created, location: @masterservice }
      else
        format.html { render :new }
        format.json { render json: @masterservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masterservices/1
  # PATCH/PUT /masterservices/1.json
  def update
    respond_to do |format|
      if @masterservice.update(masterservice_params)
        format.html { redirect_to @masterservice, notice: 'Masterservice was successfully updated.' }
        format.json { render :show, status: :ok, location: @masterservice }
      else
        format.html { render :edit }
        format.json { render json: @masterservice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masterservices/1
  # DELETE /masterservices/1.json
  def destroy
    @masterservice.destroy
    respond_to do |format|
      format.html { redirect_to masterservices_url, notice: 'Masterservice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_masterservice
      @masterservice = Masterservice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def masterservice_params
      params.require(:masterservice).permit(:name, :description)
    end
end

app/helpers/masterservices_helper.rb
module MasterservicesHelper
end

app/views/masterservices/_form.html.erb
<%= form_for(@masterservice) do |f| %>
  <% if @masterservice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@masterservice.errors.count, "error") %> prohibited this masterservice from being saved:</h2>

      <ul>
      <% @masterservice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit nil, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/masterservices/edit.html.erb
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @masterservice %> |
<%= link_to 'Back', masterservices_path %>

app/views/masterservices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Services</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @masterservices.each do |masterservice| %>
      <tr>
        <td><%= masterservice.name %></td>
        <td><%= masterservice.description %></td>
        <td><%= link_to 'Show', masterservice %></td>
        <td><%= link_to 'Edit', edit_masterservice_path(masterservice) %></td>
        <td><%= link_to 'Destroy', masterservice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Masterservice', new_masterservice_path %>

app/views/masterservices/new.html.erb
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', masterservices_path %>

app/views/masterservices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @masterservice.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @masterservice.description %>
</p>

<%= link_to 'Edit', edit_masterservice_path(@masterservice) %> |
<%= link_to 'Back', masterservices_path %>