config/routes.rb
Rails.application.routes.draw do
  resources :providerservices
  resources :providerprofiles
  resources :masterservices
  get 'pages/home'
  get 'pages/maptest'

  resources :profiles
  devise_for :providers
  devise_for :customers
  
  root 'pages#home'

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "NDIS Plus", root_path, class: "navbar-brand" %>
      
    </div>
 
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      
      
      <ul class="nav navbar-nav navbar-right">
        <% if current_customer %>
          <li><%= link_to "Profile Page", profiles_path %></li>
          <li><%= link_to "Settings", edit_customer_registration_path %></li>
          <li><%= link_to "Log Out", destroy_customer_session_path, method: :delete %></li>
        <% elsif current_provider %>
          <li><%= link_to "Services", masterservices_path %></li>
          <li><%= link_to "Profile Page", providerprofiles_path %></li>
          <li><%= link_to "Settings", edit_provider_registration_path %></li>
          <li><%= link_to "Log Out", destroy_provider_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login as Customer", new_customer_session_path %></li>
          <li><%= link_to "Login as Provider", new_provider_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
  <%= render "layouts/header" %>  
    
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>  
  
<div class="container">
  
  <%= yield %>
  
</div>


</body>
</html>